services:
  _defaults:
    autowire: true

  D3\LoggerExtension\ConfigurationExtension:
    class: D3\LoggerExtension\ConfigurationExtension
    decorates: D3\OxLogIQ\MonologConfiguration
    decoration_inner_name: 'oxlogiq_http_api.configuration.inner'
    arguments:
      - '@oxlogiq_http_api.configuration.inner'