services:
  _defaults:
    autowire: true

  D3\LoggerExtension\ConfigurationExtension:
    class: D3\LoggerExtension\ConfigurationExtension
    decorates: D3\OxLogIQ\MonologConfiguration
    decoration_inner_name: 'oxid.d3_loggerconfuguration.inner'
    arguments:
      - '@oxid.d3_loggerconfiguration.inner'